In [8]:
from datasets import load_dataset

ds = load_dataset("openlifescienceai/medmcqa")
# Display the first 5 rows of the training set
import pandas as pd

df = pd.DataFrame(ds['train'])
df.head(5)

,id,question,opa,opb,opc,opd,cop,choice_type,exp,subject_name,topic_name
0,e9ad821a-c438-4965-9f77-760819dfa155,Chronic urethral obstruction due to benign pri...,Hyperplasia,Hyperophy,Atrophy,Dyplasia,2,single,Chronic urethral obstruction because of urinar...,Anatomy,Urinary tract
1,e3d3c4e1-4fb2-45e7-9f88-247cc8f373b3,Which vitamin is supplied from only animal sou...,Vitamin C,Vitamin B7,Vitamin B12,Vitamin D,2,single,Ans. (c) Vitamin B12 Ref: Harrison's 19th ed. ...,Biochemistry,Vitamins and Minerals
2,5c38bea6-787a-44a9-b2df-88f4218ab914,All of the following are surgical options for ...,Adjustable gastric banding,Biliopancreatic diversion,Duodenal Switch,Roux en Y Duodenal By pass,3,multi,"Ans. is 'd' i.e., Roux en Y Duodenal Bypass Ba...",Surgery,Surgical Treatment Obesity
3,cdeedb04-fbe9-432c-937c-d53ac24475de,Following endaerectomy on the right common car...,Central aery of the retina,Infraorbital aery,Lacrimal aery,Nasociliary aretry,0,multi,The central aery of the retina is a branch of ...,Ophthalmology,None
4,dc6794a3-b108-47c5-8b1b-3b4931577249,Growth hormone has its effect on growth through?,Directly,IG1-1,Thyroxine,Intranuclear receptors,1,single,"Ans. is 'b' i.e., IGI-1GH has two major functi...",Physiology,None

In [14]:
# Add correct_answer column to the original dataframe
df['correct_answer'] = df.apply(lambda row: row['opa'] if row['cop'] == 0 
                                           else row['opb'] if row['cop'] == 1 
                                           else row['opc'] if row['cop'] == 2 
                                           else row['opd'] if row['cop'] == 3 
                                           else None, axis=1)

# Add complete_answer column that joins correct_answer and exp
df['complete_answer'] = df['correct_answer'] + ' | ' + df['exp']

# Add complete_question column that joins question and all options
df['complete_question'] = df['question'] + ' | Options: ' + df['opa'] + ', ' + df['opb'] + ', ' + df['opc'] + ', ' + df['opd']

# Add question_with_context column that joins subject, topic, and complete question
df['question_with_context'] = 'Subject: ' + df['subject_name'].fillna('') + ' | Topic: ' + df['topic_name'].fillna('N/A') + ' | Question: ' + df['complete_question']

# Display first few rows with all columns
df.head()

,id,question,opa,opb,opc,opd,cop,choice_type,exp,subject_name,topic_name,correct_answer,complete_answer,complete_question,question_with_context
0,e9ad821a-c438-4965-9f77-760819dfa155,Chronic urethral obstruction due to benign pri...,Hyperplasia,Hyperophy,Atrophy,Dyplasia,2,single,Chronic urethral obstruction because of urinar...,Anatomy,Urinary tract,Atrophy,Atrophy | Chronic urethral obstruction because...,Chronic urethral obstruction due to benign pri...,Subject: Anatomy | Topic: Urinary tract | Ques...
1,e3d3c4e1-4fb2-45e7-9f88-247cc8f373b3,Which vitamin is supplied from only animal sou...,Vitamin C,Vitamin B7,Vitamin B12,Vitamin D,2,single,Ans. (c) Vitamin B12 Ref: Harrison's 19th ed. ...,Biochemistry,Vitamins and Minerals,Vitamin B12,Vitamin B12 | Ans. (c) Vitamin B12 Ref: Harris...,Which vitamin is supplied from only animal sou...,Subject: Biochemistry | Topic: Vitamins and Mi...
2,5c38bea6-787a-44a9-b2df-88f4218ab914,All of the following are surgical options for ...,Adjustable gastric banding,Biliopancreatic diversion,Duodenal Switch,Roux en Y Duodenal By pass,3,multi,"Ans. is 'd' i.e., Roux en Y Duodenal Bypass Ba...",Surgery,Surgical Treatment Obesity,Roux en Y Duodenal By pass,"Roux en Y Duodenal By pass | Ans. is 'd' i.e.,...",All of the following are surgical options for ...,Subject: Surgery | Topic: Surgical Treatment O...
3,cdeedb04-fbe9-432c-937c-d53ac24475de,Following endaerectomy on the right common car...,Central aery of the retina,Infraorbital aery,Lacrimal aery,Nasociliary aretry,0,multi,The central aery of the retina is a branch of ...,Ophthalmology,None,Central aery of the retina,Central aery of the retina | The central aery ...,Following endaerectomy on the right common car...,Subject: Ophthalmology | Topic: N/A | Question...
4,dc6794a3-b108-47c5-8b1b-3b4931577249,Growth hormone has its effect on growth through?,Directly,IG1-1,Thyroxine,Intranuclear receptors,1,single,"Ans. is 'b' i.e., IGI-1GH has two major functi...",Physiology,None,IG1-1,"IG1-1 | Ans. is 'b' i.e., IGI-1GH has two majo...",Growth hormone has its effect on growth throug...,Subject: Physiology | Topic: N/A | Question: G...